const AGENTS = [
  {
    file: 'manager',
    role: 'Engineering Manager',
    character: 'Tanjiro Kamado',
    breathing: 'Water Breathing / Sun Breathing',
    why: 'Empathetic leader who unites every specialist toward the mission — never gives up on any team member',
  },
  {
    file: 'scrum',
    role: 'Scrum Master',
    character: 'Rengoku Kyojuro',
    breathing: 'Flame Breathing',
    why: 'Passionate, energetic facilitator — "SET YOUR HEART ABLAZE" — removes blockers with unmatched intensity',
  },
  {
    file: 'po',
    role: 'Product Owner',
    character: 'Kiriya Ubuyashiki',
    breathing: 'None — pure strategy',
    why: 'Translates the CEO\'s vision into actionable requirements the whole corps can execute',
  },
  {
    file: 'staff-engineer',
    role: 'Staff Engineer',
    character: 'Giyu Tomioka',
    breathing: 'Water Breathing',
    why: 'Methodical, precise — the gold standard of craft; reviews all code with quiet authority',
  },
  {
    file: 'backend',
    role: 'Backend Developer',
    character: 'Zenitsu Agatsuma',
    breathing: 'Thunder Breathing',
    why: 'Incredibly fast and focused under pressure — delivers with lightning speed when it counts',
  },
  {
    file: 'architect',
    role: 'System Architect',
    character: 'Gyomei Himejima',
    breathing: 'Stone Breathing',
    why: 'Unshakeable foundation for the whole system — the wisest voice in every design decision',
  },
  {
    file: 'qa',
    role: 'QA Engineer',
    character: 'Shinobu Kocho',
    breathing: 'Insect Breathing',
    why: 'Finds every weakness before the enemy does — precise, analytical, relentless',
  },
  {
    file: 'devops',
    role: 'DevOps Engineer',
    character: 'Tengen Uzui',
    breathing: 'Sound Breathing',
    why: '"FLAMBOYANT" — makes operations spectacular, reliable, and impossible to ignore',
  },
  {
    file: 'security',
    role: 'Security Engineer',
    character: 'Obanai Iguro',
    breathing: 'Serpent Breathing',
    why: 'Finds hidden vulnerabilities in the most twisted paths — nothing escapes the Serpent Hashira',
  },
  {
    file: 'networking',
    role: 'Domain Expert',
    character: 'Muichiro Tokito',
    breathing: 'Mist Breathing',
    why: 'Ethereal, specialized mastery of the project\'s core technical domain',
  },
  {
    file: 'documentation',
    role: 'Documentation Engineer',
    character: 'Yoriichi Tsugikuni',
    breathing: 'Sun Breathing',
    why: 'The original — legendary source of all knowledge; explains the most complex ideas with perfect clarity',
  },
  {
    file: 'researcher',
    role: 'Researcher',
    character: 'Kanao Tsuyuri',
    breathing: 'Flower Breathing',
    why: 'Highly observant, processes information with extraordinary precision',
  },
  {
    file: 'release-manager',
    role: 'Release Manager',
    character: 'Inosuke Hashibira',
    breathing: 'Beast Breathing',
    why: 'Gets it shipped by any means necessary — untamed, forceful, unstoppable',
  },
  {
    file: 'marketing',
    role: 'Marketing',
    character: 'Mitsuri Kanroji',
    breathing: 'Love Breathing',
    why: 'Makes everyone fall in love with the product — warmth and enthusiasm that converts',
  },
  {
    file: 'perf',
    role: 'Performance Engineer',
    character: 'Sanemi Shinazugawa',
    breathing: 'Wind Breathing',
    why: 'Aggressive optimization — pushes every system to its absolute limit',
  },
  {
    file: 'sre',
    role: 'Site Reliability Engineer',
    character: 'Nezuko Kamado',
    breathing: 'Blood Demon Art',
    why: 'Protects the team and users from disasters — transforms threats into resilience',
  },
  {
    file: 'tpm',
    role: 'Technical Program Manager',
    character: 'Kagaya Ubuyashiki',
    breathing: 'None — the Master sees all',
    why: 'Coordinates at the highest strategic level — tracks dependencies, milestones, and risk across the entire corps',
  },
];

// Characters available for custom roles (not yet assigned)
const RESERVE_CHARACTERS = [
  { character: 'Genya Shinazugawa', breathing: 'Demon Slayer Mark' },
  { character: 'Aoi Kanzaki', breathing: 'Water Breathing' },
  { character: 'Goto', breathing: 'None' },
  { character: 'Hotaru Haganezuka', breathing: 'None — pure craft' },
  { character: 'Kozo Kanamori', breathing: 'None — pure craft' },
  { character: 'Senjuro Rengoku', breathing: 'Flame Breathing' },
  { character: 'Sabito', breathing: 'Water Breathing' },
  { character: 'Makomo', breathing: 'Water Breathing' },
];

module.exports = { AGENTS, RESERVE_CHARACTERS };
